### ISSUE TITLE
Time shifted state-sequences in simpleSaccadeEnv do not align. How come?

### ISSUE THREAD

**Issue by LPompe** [LPompe/neurl#11]
https://github.com/LPompe/neurl/blob/a22b16ad1acd86aca16e6b2b8108afdedbed41ff/environments.py#L506-L507

This is either because the extra information (prev-action/reward), or because the `update_state` function overwrites something. Will keep an eye on it. But needs fixing before big experiments

**Comment by iocalangiu** [comment]
Hey, thanks for setting up the tests. I looked over the bug, but I think it’s fine. We abort the trial if the agent breaks fixation in the state = ‘targets_on_fixate’, that’s why the next_state is ‘end_trial’, which is a blank screen, the agent is replaced in the centre of the screen and a new trial with state = ‘targets_on_fixate’ is attempted. 

In self.switch_task_state you can see all the situations the agent gets into state ‘end_trial’, and whenever this happens, the trial is reset and agent replaced. In the future, we would want it more natural, where we only place the agent in the beginning of the session, and then it learns to place itself by exploration, but this way was faster. The concatanated ‘states’ and ‘next_states’ look something like this, in this early phase of training, where the agent is only ‘learning’ the correct policy in state = ‘targets_on_fixate’:

states:            state_1 (trial 1)          state_1 (trial 2)          state_1 (trial 3)
next_states:   blank(abort trial)      blank(abort trial)      blank(abort trial)

**Comment by LPompe** [comment]
Perfect, thanks. Makes sense. I'll adapt the test.

**Comment by LPompe** [comment]
Solved in 2c797c107501a4a98d3e33099182bf4df08c0fe9
